version: 0.2

env:
  # ===================================== #
  #  Ref: Pipeline Environment Variables  #
  # ===================================== #
  variables:
    env_aws_account: "${AWS_ACCOUNT}"
    env_aws_access_key: "${AWS_ACCESS_KEY}"
    env_aws_secret_key: "${AWS_SECRET_KEY}"
    env_repo_username: "${REPO_USERNAME}"
    env_repo_pubkey: "${REPO_PUBKEY}" # base64 encoded
    env_dockerhub_username: "${DOCKERHUB_USERNAME}"
    env_dockerhub_password: "${DOCKERHUB_PASSWORD}"
    env_repo_url: "${REPO_URL}"
    env_repo_folder: "${REPO_FOLDER}"
    env_container_image: "devopscorner/cicd:alpine"
    AWS_DEFAULT_REGION: "ap-southeast-1"
    TF_VERSION: "1.1.7"

phases:
  install:
    # Runtime Version
    # https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
    # https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
    runtime-versions:
      python: 3.8
    commands:
      - cd /usr/bin
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
  pre_build:
    commands:
      # ========================= #
      #  Using Public Repository  #
      #========================== #
      # - git clone ${STORE_REPO_URL} ${STORE_REPO_FOLDER}
      # - cd ${STORE_REPO_FOLDER} && find ./ -type f -exec sed -i "s/YOUR_AWS_ACCOUNT/${STORE_AWS_ACCOUNT}/g" {} \;
      # ====================== #
      #  Using AWS CodeCommit  #
      #======================= #
      # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
      - cd ${CODEBUILD_SRC_DIR} && find ./ -type f -exec sed -i "s/YOUR_AWS_ACCOUNT/${STORE_AWS_ACCOUNT}/g" {} \;
      - echo '- DONE -'
  build:
    commands:
      # ============= #
      #  Build Image  #
      #============== #
      - make build-cicd-alpine
      # ============ #
      #  Tags Image  #
      #============= #
      - make ecr-tag-alpine
      # ============ #
      #  Push Image  #
      #============= #
      # Login ECR (Inside Script)
      # Push to ECR
      - make ecr-push-alpine
      - echo '-- ALL DONE --'

artifacts:
  files:
    - compose/*
    - scripts/*
    - _infra/*
    - Makefile
    - README.md
    - run-docker.sh
  name: "artifact-$(date '+%Y%m%d-%H%M%S')"
