version: 0.2

env:
  # ==================== #
  #  Ref: SECRET CONFIG  #
  # ==================== #
  parameter-store:
    BUILDNUMBER: /devopscorner/cicd/lab/repo/devopscorner-container/buildnumber
    STORE_AWS_ACCOUNT: /devopscorner/cicd/lab/credentials/aws_account
    STORE_AWS_ACCESS_KEY: /devopscorner/cicd/lab/credentials/aws_access_key
    STORE_AWS_SECRET_KEY: /devopscorner/cicd/lab/credentials/aws_secret_key
    STORE_REPO_USERNAME: /devopscorner/cicd/lab/repo_credentials/codecommit/username
    STORE_REPO_PASSWORD: /devopscorner/cicd/lab/repo_credentials/codecommit/password_encoded
    STORE_DOCKERHUB_USERNAME: /devopscorner/cicd/lab/repo_credentials/dockerhub/username
    STORE_DOCKERHUB_PASSWORD: /devopscorner/cicd/lab/repo_credentials/dockerhub/password_encoded
    STORE_REPO_URL: /devopscorner/cicd/lab/repo/devopscorner-container/repo_url
    STORE_REPO_FOLDER: /devopscorner/cicd/lab/repo/devopscorner-container/repo_folder
  # ===================================== #
  #  Ref: Pipeline Environment Variables  #
  # ===================================== #
  variables:
    env_container_image: "devopscorner/devopscorner-container:alpine"
    AWS_DEFAULT_REGION: "ap-southeast-1"
    TF_VERSION: "1.1.7"

phases:
  install:
    # Runtime Version
    # https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
    # https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
    runtime-versions:
      python: 3.8
    commands:
      - cd /usr/bin
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
  pre_build:
    commands:
      - git clone ${STORE_REPO_URL} ${STORE_REPO_FOLDER}
      - cd ${env_repo_folder} && find ./ -type f -exec sed -i "s/YOUR_AWS_ACCOUNT/${STORE_AWS_ACCOUNT}/g" {} \;
      - echo '- DONE -'
  build:
    commands:
      # ============= #
      #  Build Image  #
      #============== #
      - make build-cicd-alpine
      # ============ #
      #  Tags Image  #
      #============= #
      - docker tag ${env_aws_account}.dkr.ecr.ap-southeast-1.amazonaws.com/devopscorner/cicd:alpine ${env_container_image}
      - make dockerhub-tag-alpine
      # ============ #
      #  Push Image  #
      #============= #
      # Login DockerHub (Inside Script)
      # Push to DockerHub
      - make dockerhub-push-alpine
      - echo '-- ALL DONE --'

artifacts:
  files:
    - compose/*
    - scripts/*
    - _infra/*
    - Makefile
    - README.md
    - run-docker.sh
  name: "artifact-$(date '+%Y%m%d-%H%M%S')"
