version: "3.7"

#================================================================================================
# NETWORK SETUP
#================================================================================================
networks:
  devopscorner_net:
    name: ${NETWORKS_NAME:-devopscorner_net}
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      config:
        - subnet: 172.146.146.0/16

#================================================================================================
# VOLUME SETUP
#================================================================================================
volumes:
  vol_portainer:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_PORTAINER:-/opt/data/docker/portainer2.9}
  vol_forticlient:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_FORTICLIENT:-/opt/data/docker/forticlient22.04}

services:
  #================================================================================================
  # PORTAINER
  #================================================================================================
  portainer:
    image: dockerframework/portainer:${PORTAINER_VERSION:-2.9.0}
    container_name: ${CONTAINER_PORTAINER:-devopscorner_portainer}
    restart: unless-stopped
    hostname: myportainer
    ports:
      - "${PORT_PORTAINER:-5213}:9000"
    volumes:
      # - /etc/localtime:/etc/localtime:ro        ## Do not use it in mac
      - /var/run/docker.sock:/var/run/docker.sock ## Do not use it in k8s
      - vol_portainer:/data
    environment:
      - PORTAINER_TEMPLATE=generic
      - PORTAINER_VERSION=${PORTAINER_VERSION:-2.9.0}
    privileged: true
    networks:
      devopscorner_net:
        ipv4_address: ${CONTAINER_IP_PORTAINER:-172.146.146.4}

  #================================================================================================
  # FORTICLIENT
  #================================================================================================
  forticlient:
    image: devopscorner/forticlient:${FORTICLIENT:-22.04}
    # build:
    #   context: ./forticlient
    #   dockerfile: Dockerfile
    container_name: ${CONTAINER_FORTICLIENT:-devopscorner_forticlient}
    restart: unless-stopped
    hostname: myforticlient
    environment:
      - FORTICLIENT_VERSION=${FORTICLIENT_VERSION:-22.04}
      - VPNADDR=host:port
      - VPNUSER=me@domain
      - VPNPASS=secret
      - VPNTIMEOUT=${VPNTIMEOUT:-10}
    volumes:
      # - /etc/localtime:/etc/localtime:ro        ## Do not use it in mac
      - /var/run/docker.sock:/var/run/docker.sock ## Do not use it in k8s
      - vol_forticlient:/data
    ports:
      - 8080:8080 # HTTP
      - 8443:8443 # HTTPS
    privileged: true
    networks:
      devopscorner_net:
        ipv4_address: ${CONTAINER_IP_FORTICLIENT:-172.146.146.105}
