version: '3.7'

#================================================================================================
# NETWORK SETUP
#================================================================================================
networks:
  devopscorner_net:
    name: ${NETWORKS_NAME:-devopscorner_net}
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      config:
        - subnet: 172.146.146.0/16

#================================================================================================
# VOLUME SETUP
#================================================================================================
volumes:
  vol_portainer:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_PORTAINER:-/opt/data/docker/portainer2.9}
  vol_openfortivpn:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_OPENFORTIVPN:-/opt/data/docker/openfortivpn22.04}

services:
#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    image: dockerframework/portainer:${PORTAINER_VERSION:-2.9.0}
    container_name: ${CONTAINER_PORTAINER:-devopscorner_portainer}
    restart: unless-stopped
    hostname: myportainer
    ports:
      - "${PORT_PORTAINER:-5213}:9000"
    volumes:
  #   - /etc/localtime:/etc/localtime:ro           ## Do not use it in mac
  #   - /var/run/docker.sock:/var/run/docker.sock  ## Do not use it in k8s
      - vol_portainer:/data
    environment:
      - PORTAINER_TEMPLATE=generic
      - PORTAINER_VERSION=${PORTAINER_VERSION:-2.9.0}
    privileged: true
    networks:
      devopscorner_net:
        ipv4_address: ${CONTAINER_IP_PORTAINER:-172.146.146.4}

#================================================================================================
# OPENFORTIVPN
#================================================================================================
  openfortivpn:
    image: devopscorner/openfortivpn:${OPENFORTIVPN_VERSION:-22.04}
    # build:
    #   context: ./openfortivpn
    #   dockerfile: Dockerfile
    container_name: ${CONTAINER_OPENFORTIVPN:-devopscorner_openfortivpn}
    restart: unless-stopped
    hostname: myopenfortivpn
    environment:
      - OPENFORTIVPN_VERSION=${OPENFORTIVPN_VERSION:-22.04}
      - VPN_HOST=host
      - VPN_PORT=port
      - VPN_ADDR=host:port
      - VPN_USER=user@domain
      - VPN_PASS=secret
      - VPN_TRUST_CERT=1234567890987654321
      - VPN_TIMEOUT=${VPNTIMEOUT:-10}
    volumes:
  #   - /etc/localtime:/etc/localtime:ro           ## Do not use it in mac
  #   - /var/run/docker.sock:/var/run/docker.sock  ## Do not use it in k8s
      - vol_openfortivpn:/data
    ports:
      - 5214:8080    # HTTP
      - 5215:8443    # HTTPS
    privileged: true
    networks:
      devopscorner_net:
        ipv4_address: ${CONTAINER_IP_OPENFORTIVPN:-172.146.146.105}
