FROM public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:${CODEBUILD_VERSION:-2.0}

ARG BUILD_DATE
ARG BUILD_VERSION
ARG GIT_COMMIT
ARG GIT_URL

ENV VENDOR="DevOpsCornerId"
ENV AUTHOR="DevOpsCorner.id <support@devopscorner.id>"
ENV IMG_NAME="cicd-codebuild"
ENV IMG_VERSION="2.0"
ENV IMG_DESC="Docker CodeBuild CI/CD"
ENV IMG_ARCH="amd64/x86_64"

ENV CODEBUILD_VERSION="2.0"
ENV CICD_VERSION="1.23"

LABEL maintainer="$AUTHOR" \
      architecture="$IMG_ARCH" \
      codebuild-version="$CODEBUILD_VERSION" \
      cicd-version="$CICD_VERSION" \
      org.label-schema.build-date="$BUILD_DATE" \
      org.label-schema.name="$IMG_NAME" \
      org.label-schema.description="$IMG_DESC" \
      org.label-schema.vcs-ref="$GIT_COMMIT" \
      org.label-schema.vcs-url="$GIT_URL" \
      org.label-schema.vendor="$VENDOR" \
      org.label-schema.version="$BUILD_VERSION" \
      org.label-schema.schema-version="$IMG_VERSION" \
      org.opencontainers.image.authors="$AUTHOR" \
      org.opencontainers.image.description="$IMG_DESC" \
      org.opencontainers.image.vendor="$VENDOR" \
      org.opencontainers.image.version="$IMG_VERSION" \
      org.opencontainers.image.revision="$GIT_COMMIT" \
      org.opencontainers.image.created="$BUILD_DATE" \
      fr.hbis.docker.base.build-date="$BUILD_DATE" \
      fr.hbis.docker.base.name="$IMG_NAME" \
      fr.hbis.docker.base.vendor="$VENDOR" \
      fr.hbis.docker.base.version="$BUILD_VERSION"

COPY rootfs /

ENV ANSIBLE_VERSION=2.12.2
# ENV ANSIBLE_TOWER_CLI_VERSION=3.3.9   # Depreciated, change to AWX-Cli (awxkit)
ENV AWXKIT_VERSION=21.9.0
ENV PACKER_VERSION=1.8.6
ENV TERRAFORM_VERSION=1.3.9
ENV TERRAGRUNT_VERSION=v0.43.2
ENV TERRASCAN_VERSION=1.18.0
ENV HELMFILE_VERSION=v0.144.0
ENV KUBECTL_VERSION=v1.26.1
ENV CHECKOV_VERSION=2.3.21
ENV AWS_CLI_VERSION=2.10.0
ENV VERIFY_CHECKSUM=false

USER root
RUN yum update -y; sync
RUN yum groupinstall "Development Tools" -y; sync

RUN yum install -y \
      git \
      curl \
      zip \
      unzip \
      wget; sync

RUN yum install -y \
      bash \
      jq \
      vim-enhanced \
      telnet \
      openssl11 \
      openssl11-devel \
      libffi-devel \
      bzip2-devel \
      python37 \
      python3-pip; sync

# ==================== #
#  Install Terragrunt  #
# ==================== #
RUN wget -O /usr/local/bin/terragrunt \
      https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 &&\
      chmod +x /usr/local/bin/terragrunt; sync &&\
      # ================ #
      #  Install Packer  #
      # ================ #
      wget -O packer_${PACKER_VERSION}_linux_amd64.zip \
      https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip &&\
      unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /usr/local/bin &&\
      rm -f packer_${PACKER_VERSION}_linux_amd64.zip; sync &&\
      # =================== #
      #  Install Terrascan  #
      # =================== #
      wget -O terrascan.tar.gz \
      https://github.com/accurics/terrascan/releases/download/v${TERRASCAN_VERSION}/terrascan_${TERRASCAN_VERSION}_Linux_x86_64.tar.gz &&\
      tar -zxf terrascan.tar.gz -C /usr/local/bin &&\
      chmod +x /usr/local/bin/terrascan &&\
      rm terrascan.tar.gz; sync &&\
      # =================== #
      #  Install Infracost  #
      # =================== #
      curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | bash; sync

# =============== #
#  Install TFSec  #
# =============== #
RUN curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash; sync
# COPY --from=aquasec/tfsec:latest /usr/bin/tfsec /usr/local/bin/tfsec

# =============== #
#  Install TFenv  #
# =============== #
RUN git clone https://github.com/tfutils/tfenv.git ~/.tfenv &&\
      echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bashrc; sync &&\
      ln -sf ~/.tfenv/bin/* /usr/local/bin &&\
      mkdir -p ~/.local/bin/ &&\
      ln -sf ~/.tfenv/bin/* ~/.local/bin; sync

# =================== #
#  Install Terraform  #
# =================== #
RUN /usr/local/bin/tfenv install ${TERRAFORM_VERSION} &&\
      /usr/local/bin/terraform use ${TERRAFORM_VERSION}; sync &&\
      /usr/local/bin/terraform version; sync

# ============== #
#  Install Helm  #
# ============== #
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 &&\
      chmod +x get_helm.sh &&\
      ./get_helm.sh &&\
      helm version; sync

# ===================== #
#  Install Helm Plugins #
# ===================== #
RUN helm plugin install https://github.com/databus23/helm-diff &&\
      helm plugin install https://github.com/hypnoglow/helm-s3.git &&\
      helm repo add stable https://charts.helm.sh/stable &&\
      helm repo update; sync

# ================== #
#  Install Helmfile  #
# ================== #
RUN wget -O /usr/local/bin/helmfile \
      https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_linux_amd64 &&\
      chmod +x /usr/local/bin/helmfile &&\
      helmfile --version; sync

# ================= #
#  Install Kubectl  #
# ================= #
RUN wget -O /usr/local/bin/kubectl \
      https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&\
      chmod +x /usr/local/bin/kubectl; sync

# ================ #
#  Install AWSCli  #
# ================ #
RUN curl -s https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip -o awscliv2.zip &&\
      unzip awscliv2.zip &&\
      ./aws/install; sync

# ========================= #
# Install Python Libraries  #
# ========================= #
RUN python3 -m pip install pip &&\
      pip3 install --upgrade pip==22.3.1 cffi &&\
      # ================= #
      #  Install Ansible  #
      # ================= #
      pip3 install --no-cache-dir \
      ansible-core==${ANSIBLE_VERSION} \
      # ansible-tower-cli==${ANSIBLE_TOWER_CLI_VERSION} \
      awxkit==${AWXKIT_VERSION} \
      PyYaml \
      Jinja2 \
      httplib2 \
      six \
      requests \
      boto3 \
      # ================= #
      #  Install Checkov  #
      # ================= #
      checkov==${CHECKOV_VERSION} &&\
      # setup root .ssh directory
      mkdir -p /root/.ssh &&\
      chmod 0700 /root/.ssh &&\
      chown -R root. /root/.ssh; sync

RUN chmod +x /tmp/*.sh

# ============= #
#  Cleanup All  #
# ============= #
RUN yum clean all; sync

WORKDIR /root

EXPOSE 22 80